### ISSUE TITLE
ProviderUpdated should fire twice for both Provider change and State Changed

### ISSUE THREAD

**Issue by michael-hawker** [windows-toolkit/Graph-Controls#16]
If you listen to the ProviderUpdated on initialization of an application, you'll never get a 'SignedIn' event after the Provider changed, even though it's already signed-in from the token, we should still send the event so logic can be simplified in apps to understand that they've signed-in.

**Comment by michael-hawker** [comment]
Somewhat related to #9

**Comment by shweaver-MSFT** [comment]
This is interesting, because in one way it does simplify separating the logical paths between when a global provider is set, versus when the state changes. But it actually breaks my primary pattern for checking when the global provider is set on app startup:

```
ProviderManager.Instance.ProviderUpdated += (s, e)
{
    var provider = ProviderManager.Instance.GlobalProvider;
    if (provider?.State == ProviderState.SignedIn)
    {
        // I am signed in!
    }
};

ProviderManager.Instance.GlobalProvider = new MockProvider();
```

This logic would now fire twice, so I MUST check the reason before deciding to act:

```
ProviderManager.Instance.ProviderUpdated += (s, e)
{
    var provider = ProviderManager.Instance.GlobalProvider;
    if (e.Reason == ProviderManagerChangedState.ProviderStateChanged && provider?.State == ProviderState.SignedIn)
    {
        // I am signed in!
    }
};

ProviderManager.Instance.GlobalProvider = new MockProvider();
```

It's a small thing, but worth pointing out.

**Comment by michael-hawker** [comment]
Wondering since we have the PropertyChanged event on GlobalProvider if we need to even have the ProviderChanged reason here. Like effectively just have two separate types of events for the provider changing vs. the state changing. (I mean providers changing should be rare, right?)

What does MGT do currently for this? I thought I remember we had similar discussions on how this worked for the Login Button over there way back when?

**Comment by michael-hawker** [comment]
@shweaver-MSFT probably should have left this comment on the PR instead of here, but wanted to make sure you saw it.

**Comment by shweaver-MSFT** [comment]
Well, MGT kind of matches our current implementation. It emits an event for either ProviderChanged or ProviderStateChanged. However, nothing in the entire project listens to those events directly. Instead, to listen for changes there is a function in Providers that accepts a callback and only triggers when the provider state changes. 

So looking at MGT, it seems that the best pattern is to hook into the GlobalProvider owner (`Providers` for MGT, `ProviderManager` in our case) to listen for changes in the provider state, `ProviderStateChanged`. This prevents the need to check if the GlobalProvider has been set or not, because we mostly care about responding to the state changes. However, for cases where we really do care that the GlobalProvider instance has changed, we should have a separate event, `ProviderChanged`.

So ultimately, I think we should have two distinct, separate events for detecting changes in the global provider, `ProviderChanged` and `ProviderStateChanged`. 

I like `ProviderChanged` over `PropertyChanged`, because it removes the extra step of checking the property name.
`PropertyChanged` is too ambiguous and should be removed imo.

I also like the idea of having separate events on ProviderManager instead of using a method to accept a callback like MGT does.

@michael-hawker does that sound fair to you?

**Comment by shweaver-MSFT** [comment]
@michael-hawker the PR is up if you care to take a look #112 :)
