### ISSUE TITLE
PromptBehavior for Microsoft Graph should be set to SelectAccount by default

### ISSUE THREAD

**Issue by nmetulev** [windows-toolkit/Graph-Controls#49]
## I'm submitting a...

- Default value change

## Current behavior

See comment [here](https://github.com/Microsoft/WindowsCommunityToolkit/pull/2340#discussion_r206987389)

> This Prompt behavior is bad. It should be `SelectAccount` by default so that it can leverage Connected To Windows accounts.

> https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory.promptbehavior?view=azure-dotnet

Need to test fully to make sure this change does not break anything.

**Comment by michael-hawker** [comment]
@nmetulev I'm not sure if this is still an issue with our new API surface. Is there something I should look for at the MSAL layer to understand our current behavior vs. what it should be?

**Comment by nmetulev** [comment]
TBH, I don't remember and it's been a while since I've looked at how to set the prompt behavior in msal.net. It is possible this was already fixed in the sdk and this issue can be closed

**Comment by HerrickSpencer** [comment]
From the MSAL team I might be able to share some possible context here.  The SSO that supports the select_account header doesn't work well in UWP if that is what was being used for this issue. You need to take some steps to enable it, one of which is to add a redirect for the sso, and enable https://sso in the client permissions. I have some details I can share if this is suspected as the issue.  However, there's not a really good fix for the toolkit since it needs to be enabled per app registration. 

It is also evident from my investigation and work with MSAL that the issue likely rides on how the graph sdk is using cached auth. It seems to simply default to the first, with no option for selection of previous accounts.

**Comment by shweaver-MSFT** [comment]
Based on the docs, `SelectAccount` is the default for backwards-compatibility reasons, so it doesn't need to be updated. 

However, the docs also state that `NoPrompt` is the preferred value to use:

> "This [SelectAccount] is the default prompt for backwards compatibility reasons. Please use NoPrompt for the best user experience."

https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.prompt

I'm not convinced we actually need to make the change to NoPrompt, and SelectAccount is already the default, so I'm closing this until we have an actual reason to do things differently.
